##
##  Makefile -- Build procedure for sample mathtex Apache module
##  Autogenerated via ``apxs -n mathtex -g''.
##

builddir=.
include $(builddir)/definition.mk
include $(top_srcdir)/build/special.mk
#include /usr/share/apache2/build/special.mk

#   the used tools
# include from definition.mk
#APXS = @APXS@
#APACHECTL = @APACHECTL@

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
#INCLUDES=-Imy/include/dir
INCLUDES=`pkg-config --cflags apr-1` `apreq2-config --includes`
LIBS = `pkg-config --libs apr-1` `apreq2-config --ldflags --includes` -lapreq2
#LIBS=-Lmy/lib/dir -lmylib
#WC =-Wc
CFLAGS = $(INCLUDES) $(LIBS)

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules-yes

#   cleanup
clean:
	-rm -f mod_mathtex.o mod_mathtex.lo mod_mathtex.slo mod_mathtex.la 

#   simple test
test: reload
	lynx -mime_header http://localhost/mathtex

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

